# coding: utf-8

"""
    Manager

    Subscription management and related services.

    The version of the OpenAPI document: 1.0
    Contact: hello@wordlift.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from manager_client.api.embedding_api import EmbeddingApi


class TestEmbeddingApi(unittest.TestCase):
    """EmbeddingApi unit test stubs"""

    def setUp(self) -> None:
        self.api = EmbeddingApi()

    def tearDown(self) -> None:
        pass

    def test_create_embedding(self) -> None:
        """Test case for create_embedding

        Create
        """
        pass


if __name__ == '__main__':
    unittest.main()
