# coding: utf-8

"""
    Manager

    Subscription management and related services.

    The version of the OpenAPI document: 1.0
    Contact: hello@wordlift.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from manager_client.api.vector_search_questions_api import VectorSearchQuestionsApi


class TestVectorSearchQuestionsApi(unittest.TestCase):
    """VectorSearchQuestionsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = VectorSearchQuestionsApi()

    def tearDown(self) -> None:
        pass

    def test_create_vector_search_question(self) -> None:
        """Test case for create_vector_search_question

        Create
        """
        pass


if __name__ == '__main__':
    unittest.main()
