# coding: utf-8

"""
    Manager

    Subscription management and related services.

    The version of the OpenAPI document: 1.0
    Contact: hello@wordlift.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from manager_client.api.data_uri_api import DataURIApi


class TestDataURIApi(unittest.TestCase):
    """DataURIApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DataURIApi()

    def tearDown(self) -> None:
        pass

    def test_get(self) -> None:
        """Test case for get

        Get the Web Data URI for a Web Page URL.
        """
        pass


if __name__ == '__main__':
    unittest.main()
