# coding: utf-8

"""
    Manager

    Subscription management and related services.

    The version of the OpenAPI document: 1.0
    Contact: hello@wordlift.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from manager_client.api.include_excludes_word_press_plugin_api import IncludeExcludesWordPressPluginApi


class TestIncludeExcludesWordPressPluginApi(unittest.TestCase):
    """IncludeExcludesWordPressPluginApi unit test stubs"""

    def setUp(self) -> None:
        self.api = IncludeExcludesWordPressPluginApi()

    def tearDown(self) -> None:
        pass

    def test_list_include_excludes(self) -> None:
        """Test case for list_include_excludes

        List
        """
        pass

    def test_update_include_excludes(self) -> None:
        """Test case for update_include_excludes

        Update
        """
        pass


if __name__ == '__main__':
    unittest.main()
